apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
        part-of: nexus
    spec:
      containers:
        - name: nexus
          image: dendipradigta/nexus3-custom:1.1
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "300m"
          ports:
            - containerPort: 8081
 
          volumeMounts:
            - mountPath: "/nexus-data"
              name: nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
 