apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: staging2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: dendipradigta/nexus3-custom:1.1
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1.5Gi"
              cpu: "250m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}